exclude: "^pipeline/components/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
  # - repo: https://github.com/python-poetry/poetry
  #   rev: "1.2.0rc1" # add version here
  #   hooks:
  #     - id: poetry-check
  # - id: poetry-lock
  # - id: poetry-export
  # args: ["-f", "requirements.txt", "-o", "requirements.txt"]
